using Crm.Entities.Common;
using Crm.Entities.Tenancy;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Crm.Entities.Tax
{
    public class TaxCalendar : TenantEntity
    {
        public Guid CompanyId { get; set; }
        public Company Company { get; set; } = default!;
        [Required, MaxLength(EntityConstants.CodeMax)]
        public string TaxCode { get; set; } = default!;
        [Required, MaxLength(EntityConstants.TitleMax)]
        public string Description { get; set; } = default!;
        public int FiscalYear { get; set; }
        public int PeriodMonth { get; set; }
        public DateTime DeclarationDueDate { get; set; }
        public DateTime PaymentDueDate { get; set; }
        public DateTime? DeclarationSubmittedDate { get; set; }
        public DateTime? PaymentCompletedDate { get; set; }
        [MaxLength(EntityConstants.MediumTextMax)]
        public string? Notes { get; set; }
        public bool IsCompleted { get; set; } = false;
        public bool IsAutoGenerated { get; set; } = true;
    }
}
